CREATE TABLE MOVIES (
  MOVIE_ID  INTEGER PRIMARY KEY,
  MOVIE_NAME VARCHAR(30),
  LANGU VARCHAR(20),
  GENRE VARCHAR(30)
);

CREATE TABLE THEATRE (
  THEATRE_ID  INTEGER PRIMARY KEY,
  THEATRE_NAME VARCHAR(30),
  LOCATION VARCHAR(30)
);

CREATE TABLE MOVIE_SHOW (
  SHOW_ID INTEGER,
  MOVIE_ID INTEGER FOREIGN KEY REFERENCES MOVIES (MOVIE_ID),
  THEATRE_ID INTEGER FOREIGN KEY REFERENCES THEATRE (THEATRE_ID),
  SCREEN_ID VARCHAR(10),
  SHOW_TIME VARCHAR(10),
  SEAT INTEGER,
  STATUS INTEGER,
  PRIMARY KEY (SHOW_ID, MOVIE_ID, THEATRE_ID, SCREEN_ID, SHOW_TIME, SEAT)
);
 
CREATE TABLE BOOKING (
  BOOKING_ID UUID,
  SHOW_ID INTEGER,
  SEAT INTEGER,
  PRIMARY KEY (BOOKING_ID, SHOW_ID, SEAT)
); 


  